// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraficLight.BusinessLogic.Entities;

namespace TraficLight.BusinessLogic.Migrations
{
    [DbContext(typeof(TraficContext))]
    [Migration("20190703133610_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("TraficLight.BusinessLogic.Entities.Sequence", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Broken");

                    b.Property<byte>("CurentDeep");

                    b.Property<int>("FirstMissing");

                    b.Property<bool>("IsNotFirst");

                    b.Property<int>("SecondMissing");

                    b.Property<string>("Start");

                    b.Property<int>("StartNum");

                    b.HasKey("Id");

                    b.ToTable("Sequences");
                });
#pragma warning restore 612, 618
        }
    }
}
